export { FlowPilotHome as FlowPilotCRM } from './flowpilot/FlowPilotHome'
export { FlowPilotHome } from './flowpilot/FlowPilotHome'
export { FlowPilotFeatures } from './flowpilot/FlowPilotFeatures'
export { FlowPilotBenefits } from './flowpilot/FlowPilotBenefits'
export { FlowPilotIntegrations } from './flowpilot/FlowPilotIntegrations'
export { FlowPilotPricing } from './flowpilot/FlowPilotPricing'
export { FlowPilotTrial } from './flowpilot/FlowPilotTrial'
