import { useEffect, useState, type ReactNode } from 'react'
import {
  ArrowRight,
  CalendarCheck,
  Check,
  ClipboardCheck,
  FileText,
  Home,
  KeyRound,
  MailCheck,
  Menu,
  MessageSquareText,
  RefreshCw,
  ShieldCheck,
  UsersRound,
  Wrench,
  X,
} from 'lucide-react'
import heroImage from '../../assets/images/realestate/oakline/hero.png'
import landlordImage from '../../assets/images/realestate/oakline/landlord.png'
import tenantImage from '../../assets/images/realestate/oakline/tenant.png'
import propertyImage from '../../assets/images/realestate/oakline/property.png'
import serviceImage from '../../assets/images/realestate/oakline/core-service.png'
import managementImage from '../../assets/images/realestate/oakline/management.png'
import maintenanceImage from '../../assets/images/realestate/oakline/maintenance.png'
import operationsImage from '../../assets/images/realestate/oakline/operations.png'
import singleFamilyImage from '../../assets/images/realestate/oakline/single-family-rentals.png'
import apartmentsImage from '../../assets/images/realestate/oakline/apartments.png'
import multifamilyImage from '../../assets/images/realestate/oakline/multifamily.png'
import ctaImage from '../../assets/images/realestate/oakline/cta.png'

const navLinks = [['Landlords', '#landlords'], ['Tenants', '#tenants'], ['Services', '#services'], ['Maintenance', '#maintenance'], ['Contact', '#contact']]

const supportCards = [
  { image: landlordImage, label: 'Landlord support', title: 'Landlords', text: 'Organized property oversight, tenant communication, leasing coordination, and service support designed to protect long-term value.', href: '#landlords' },
  { image: tenantImage, label: 'Tenant support', title: 'Tenants', text: 'Clear communication, responsive maintenance coordination, and helpful support for a better rental experience.', href: '#tenants' },
  { image: propertyImage, label: 'Managed portfolio', title: 'Property Portfolios', text: 'Structured operations for single properties, small portfolios, and growing landlord needs.', href: '#property-types' },
]

const services = [
  { icon: CalendarCheck, title: 'Rent Collection Support', text: 'Organized reminders, documentation, and owner-facing updates.' },
  { icon: Wrench, title: 'Maintenance Coordination', text: 'Requests reviewed, assigned, communicated, and followed through.' },
  { icon: MessageSquareText, title: 'Tenant Communication', text: 'Clear, professional updates across everyday property needs.' },
  { icon: KeyRound, title: 'Leasing Support', text: 'Practical coordination for inquiries, showings, and documentation.' },
  { icon: ClipboardCheck, title: 'Property Inspections', text: 'Structured observations and documented property condition notes.' },
  { icon: UsersRound, title: 'Vendor Coordination', text: 'Reliable communication with qualified service providers.' },
  { icon: FileText, title: 'Owner Reporting', text: 'Useful summaries that make property activity easier to follow.' },
  { icon: RefreshCw, title: 'Move-In / Move-Out Support', text: 'Consistent checklists and clear transition coordination.' },
]

function OakButton({ href, children, secondary = false, className = '' }: { href: string; children: ReactNode; secondary?: boolean; className?: string }) {
  return <a href={href} className={`group inline-flex min-h-12 items-center justify-center gap-2 rounded-full px-6 text-sm font-extrabold transition duration-300 hover:-translate-y-0.5 ${secondary ? 'border border-[#BFCFC9] bg-white text-[#16324A] hover:border-[#3D7657]' : 'bg-[#3D7657] text-white shadow-[0_12px_28px_rgba(61,118,87,.2)] hover:bg-[#326549]'} ${className}`}>{children}<ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></a>
}

function OakHeading({ label, title, text, center = false, light = false }: { label: string; title: string; text?: string; center?: boolean; light?: boolean }) {
  return <div className={center ? 'mx-auto max-w-4xl text-center' : 'max-w-3xl'}><p className="text-[0.66rem] font-black uppercase tracking-[0.24em] text-[#3D7657]">{label}</p><h2 className={`mt-4 text-[clamp(2.35rem,5vw,4.8rem)] font-black leading-[0.96] tracking-[-0.055em] ${light ? 'text-white' : 'text-[#16324A]'}`}>{title}</h2>{text && <p className={`mt-6 max-w-2xl text-base leading-8 md:text-lg ${center ? 'mx-auto' : ''} ${light ? 'text-white/65' : 'text-[#607078]'}`}>{text}</p>}</div>
}

function OakLogo({ light = false }: { light?: boolean }) {
  return <a href="#home" className={`flex items-center gap-3 ${light ? 'text-white' : 'text-[#16324A]'}`} aria-label="Oakline Property Management home"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#3D7657] text-white"><Home className="h-5 w-5" /></span><span><strong className="block text-base font-black leading-none tracking-[-0.025em]">Oakline</strong><span className={`mt-1 block text-[0.53rem] font-bold uppercase tracking-[0.18em] ${light ? 'text-white/50' : 'text-[#6D7E78]'}`}>Property Management</span></span></a>
}

export function OaklinePropertyManagement() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [activeSection, setActiveSection] = useState('')

  useEffect(() => {
    const sectionIds = navLinks.map(([, href]) => href.slice(1))
    const sections = sectionIds
      .map((id) => document.getElementById(id))
      .filter((section): section is HTMLElement => section !== null)

    const observer = new IntersectionObserver(
      (entries) => {
        const visibleSection = entries
          .filter((entry) => entry.isIntersecting)
          .sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0]

        if (visibleSection) setActiveSection(visibleSection.target.id)
      },
      { rootMargin: '-24% 0px -58% 0px', threshold: [0.05, 0.2, 0.5] },
    )

    sections.forEach((section) => observer.observe(section))
    return () => observer.disconnect()
  }, [])

  return (
    <main className="oakline-site overflow-hidden bg-[#F2F7F5] text-[#334047] selection:bg-[#8FA377] selection:text-white">
      <header className="fixed inset-x-0 top-0 z-50 border-b border-[#D9E2E0] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex h-[4.5rem] max-w-[90rem] items-center justify-between px-5 lg:px-10"><OakLogo /><nav className="hidden items-center gap-2 lg:flex" aria-label="Oakline navigation">{navLinks.map(([label, href]) => { const isActive = activeSection === href.slice(1); return <a key={label} href={href} aria-current={isActive ? 'location' : undefined} className={`rounded-full px-4 py-2 text-sm font-bold transition ${isActive ? 'oakline-nav-active bg-[#E8F0EC] text-[#3D7657]' : 'text-[#5D6C72] hover:bg-[#F2F7F5] hover:text-[#3D7657]'}`}>{label}</a> })}</nav><OakButton href="#contact" className="hidden lg:inline-flex">Request Management</OakButton><button type="button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation" aria-expanded={menuOpen} className="grid h-11 w-11 place-items-center rounded-xl border border-[#D9E2E0] text-[#16324A] lg:hidden">{menuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div>{menuOpen && <nav className="border-t border-[#D9E2E0] bg-white px-5 py-5 lg:hidden">{navLinks.map(([label, href]) => { const isActive = activeSection === href.slice(1); return <a key={label} href={href} aria-current={isActive ? 'location' : undefined} onClick={() => setMenuOpen(false)} className={`block rounded-xl px-3 py-3 font-bold transition ${isActive ? 'oakline-nav-active bg-[#E8F0EC] text-[#3D7657]' : 'text-[#536369] hover:bg-[#F2F7F5]'}`}>{label}</a> })}<OakButton href="#contact" className="mt-3 w-full">Request Management</OakButton></nav>}</header>

      <section id="home" className="relative pt-[4.5rem]"><div className="mx-auto grid min-h-[47rem] max-w-[100rem] lg:grid-cols-[.9fr_1.1fr]"><div className="relative flex items-center bg-[#F2F7F5] px-5 py-20 lg:px-12 xl:px-20"><div className="absolute left-0 top-24 h-48 w-2 rounded-r-full bg-[#8FA377]" /><div><p className="inline-flex items-center gap-2 rounded-full border border-[#CAD9D4] bg-white px-4 py-2 text-[0.65rem] font-black uppercase tracking-[0.2em] text-[#3D7657]"><ShieldCheck className="h-4 w-4" /> Property management</p><h1 className="mt-7 max-w-3xl text-[clamp(3.4rem,6.2vw,6.5rem)] font-black leading-[0.9] tracking-[-0.07em] text-[#16324A]">Calm, Clear Property Management <span className="text-[#3D7657]">for Landlords and Tenants</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#607078]">Oakline Property Management helps landlords protect their properties and tenants feel supported through responsive service, organized operations, and transparent communication.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><OakButton href="#landlords">For Landlords</OakButton><OakButton href="#tenants" secondary>For Tenants</OakButton></div></div></div><div className="relative min-h-[36rem]"><img src={heroImage} alt="Well-maintained modern apartment property managed by Oakline" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#16324A]/35 via-transparent to-transparent" /><div className="absolute bottom-6 left-5 right-5 rounded-2xl border border-white/50 bg-white/92 p-5 shadow-2xl backdrop-blur md:left-8 md:right-auto md:w-80"><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#E8F0EC] text-[#3D7657]"><MailCheck className="h-5 w-5" /></span><span className="rounded-full bg-[#DDE8D4] px-3 py-1 text-[0.6rem] font-black uppercase tracking-[0.14em] text-[#3D7657]">Service focused</span></div><h2 className="mt-5 text-xl font-black text-[#16324A]">Clear updates, without the chase.</h2><p className="mt-2 text-sm leading-6 text-[#607078]">Organized requests, documented follow-up, and practical next steps.</p></div></div></div><div className="mx-auto grid max-w-[90rem] -translate-y-1/2 grid-cols-1 overflow-hidden rounded-2xl border border-[#D9E2E0] bg-white shadow-xl sm:grid-cols-3">{[[Wrench, 'Responsive Maintenance'], [ClipboardCheck, 'Transparent Operations'], [UsersRound, 'Landlord & Tenant Support']].map(([Icon, label]) => { const InfoIcon = Icon as typeof Wrench; return <div key={label as string} className="flex items-center gap-3 border-b border-[#D9E2E0] px-5 py-5 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><InfoIcon className="h-5 w-5 text-[#3D7657]" /><span className="text-sm font-black text-[#16324A]">{label as string}</span></div> })}</div></section>

      <section className="px-5 pb-24 pt-8 lg:px-10 lg:pb-32"><div className="mx-auto max-w-[90rem]"><OakHeading label="Who we help" title="Support for Every Side of the Property" text="Dependable management starts by understanding what owners, tenants, and growing portfolios need day to day." /><div className="mt-12 grid gap-6 md:grid-cols-3">{supportCards.map((card) => <article key={card.title} className="oak-card group overflow-hidden rounded-[1.5rem] border border-[#D9E2E0] bg-white"><div className="aspect-[4/3] overflow-hidden"><img src={card.image} alt="" className="h-full w-full object-cover transition duration-600 group-hover:scale-105" /></div><div className="p-7"><p className="text-[0.62rem] font-black uppercase tracking-[0.18em] text-[#8FA377]">{card.label}</p><h3 className="mt-3 text-2xl font-black tracking-[-0.04em] text-[#16324A]">{card.title}</h3><p className="mt-3 text-sm leading-7 text-[#64747A]">{card.text}</p><a href={card.href} className="mt-5 inline-flex items-center gap-2 text-sm font-black text-[#3D7657]">Learn More <ArrowRight className="h-4 w-4" /></a></div></article>)}</div></div></section>

      <section id="services" className="border-y border-[#D9E2E0] bg-white px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[90rem]"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><OakHeading label="Property management" title="Property Management Services Built Around Clarity" /><div className="relative hidden overflow-hidden rounded-2xl lg:block"><img src={serviceImage} alt="Oakline property management service coordination" className="h-60 w-full object-cover" /><div className="absolute inset-0 bg-[#16324A]/20" /></div></div><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{services.map(({ icon: Icon, title, text }) => <article key={title} className="oak-card rounded-2xl border border-[#D9E2E0] bg-[#F8FBFA] p-6"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#E8F0EC] text-[#3D7657]"><Icon className="h-5 w-5" /></span><h3 className="mt-5 font-black text-[#16324A]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#68787E]">{text}</p></article>)}</div></div></section>

      <section id="landlords" className="px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-[90rem] overflow-hidden rounded-[2rem] bg-[#16324A] lg:grid-cols-2"><div className="flex items-center p-8 text-white md:p-12 lg:p-16"><div><OakHeading label="Landlord services" title="Protect Your Property with Organized Management" text="We help landlords reduce day-to-day stress with structured communication, maintenance coordination, vendor follow-up, and clear operational routines." light /><div className="mt-8 grid gap-3 sm:grid-cols-2">{['Clear owner communication', 'Maintenance request coordination', 'Tenant support and follow-up', 'Organized property oversight'].map((item) => <div key={item} className="flex items-center gap-3 rounded-xl bg-white/[0.07] px-4 py-3 text-sm font-bold"><Check className="h-5 w-5 rounded-full bg-[#8FA377] p-1" />{item}</div>)}</div><OakButton href="#contact" className="mt-8">Request Management</OakButton></div></div><img src={managementImage} alt="Organized residential property management for landlords" className="h-full min-h-[36rem] w-full object-cover" /></div></section>

      <section id="tenants" className="bg-[#E8F0EC] px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-[90rem] gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div className="relative overflow-hidden rounded-[2rem]"><img src={tenantImage} alt="Comfortable tenant experience in an Oakline managed home" className="min-h-[35rem] w-full object-cover" /><div className="absolute bottom-6 left-6 rounded-2xl bg-white/92 p-5 shadow-xl backdrop-blur"><p className="text-[0.62rem] font-black uppercase tracking-[0.18em] text-[#3D7657]">Tenant support</p><p className="mt-1 font-black text-[#16324A]">Helpful answers. Practical next steps.</p></div></div><div><OakHeading label="Tenant support" title="A Better Rental Experience Starts with Responsive Service" text="Tenants need clear answers, timely updates, and a simple way to get help when something needs attention. Oakline keeps communication calm, organized, and helpful." /><div className="mt-8 grid gap-3">{[[Wrench, 'Maintenance Help', 'A clear path for reporting issues and receiving practical updates.'], [KeyRound, 'Move-In Guidance', 'Organized information to make the transition into a new home easier.'], [MessageSquareText, 'Clear Communication', 'Professional responses and documented next steps across property needs.']].map(([Icon, title, text]) => { const SupportIcon = Icon as typeof Wrench; return <article key={title as string} className="flex gap-4 rounded-2xl border border-white bg-white p-5"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#E8F0EC] text-[#3D7657]"><SupportIcon className="h-5 w-5" /></span><div><h3 className="font-black text-[#16324A]">{title as string}</h3><p className="mt-1 text-sm leading-6 text-[#68787E]">{text as string}</p></div></article> })}</div></div></div></section>

      <section id="maintenance" className="px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[90rem]"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><OakHeading label="Maintenance coordination" title="Maintenance Coordination Without the Confusion" text="From routine repairs to urgent service requests, our process helps keep property issues organized, documented, and moving forward." /><img src={maintenanceImage} alt="Maintenance coordination for a managed rental property" className="mt-8 h-64 w-full rounded-2xl object-cover" /></div><div className="grid gap-4 sm:grid-cols-2">{[['01', 'Request Received', 'Maintenance issue is reviewed and categorized.'], ['02', 'Vendor Coordinated', 'The right service provider is contacted when needed.'], ['03', 'Updates Shared', 'Landlords and tenants receive clear communication.'], ['04', 'Issue Followed Through', 'Work is tracked until the issue is resolved or next steps are clear.']].map(([number, title, text]) => <article key={number} className="rounded-[1.5rem] border border-[#D9E2E0] bg-white p-7"><span className="grid h-11 w-11 place-items-center rounded-full bg-[#8FA377] text-sm font-black text-white">{number}</span><h3 className="mt-6 text-xl font-black text-[#16324A]">{title}</h3><p className="mt-3 text-sm leading-7 text-[#68787E]">{text}</p></article>)}</div></div></div></section>

      <section className="relative bg-[#16324A] px-5 py-24 text-white lg:px-10 lg:py-32"><img src={operationsImage} alt="Transparent property management operations" className="absolute inset-0 h-full w-full object-cover opacity-10" /><div className="relative mx-auto max-w-[90rem]"><OakHeading label="Transparent operations" title="Clear Systems. Calm Communication. Better Oversight." text="Our approach is designed around transparency, documentation, and dependable follow-through so landlords and tenants know what is happening." light /><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[[ClipboardCheck, 'Documented Requests', 'Property needs are logged with context and useful next steps.'], [FileText, 'Organized Reporting', 'Owners receive practical summaries of relevant property activity.'], [UsersRound, 'Vendor Follow-Up', 'Service coordination includes communication after assignment.'], [MessageSquareText, 'Consistent Communication', 'Clear updates help reduce uncertainty for everyone involved.']].map(([Icon, title, text]) => { const ValueIcon = Icon as typeof ClipboardCheck; return <article key={title as string} className="rounded-2xl border border-white/12 bg-white/[0.055] p-6 backdrop-blur"><ValueIcon className="h-6 w-6 text-[#AFC39A]" /><h3 className="mt-8 text-xl font-black">{title as string}</h3><p className="mt-3 text-sm leading-7 text-white/55">{text as string}</p></article> })}</div></div></section>

      <section id="property-types" className="bg-white px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[90rem]"><OakHeading label="Managed portfolio" title="Management for Practical Rental Portfolios" text="Flexible operating support for common residential property types and evolving ownership needs." /><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[[singleFamilyImage, 'Single-Family Rentals', 'Dedicated oversight for individual homes and long-term rental operations.'], [apartmentsImage, 'Apartment Buildings', 'Coordinated resident communication and property routines across multiple units.'], [multifamilyImage, 'Small Multi-Family', 'Structured support that keeps shared property needs organized and visible.'], [propertyImage, 'Mixed Residential Portfolios', 'Consistent management practices across varied residential holdings.']].map(([image, title, text]) => <article key={title} className="oak-card group overflow-hidden rounded-[1.5rem] border border-[#D9E2E0] bg-[#F8FBFA]"><div className="aspect-[4/3] overflow-hidden"><img src={image} alt={title} className="h-full w-full object-cover transition duration-600 group-hover:scale-105" /></div><div className="p-6"><h3 className="text-xl font-black text-[#16324A]">{title}</h3><p className="mt-3 text-sm leading-7 text-[#68787E]">{text}</p></div></article>)}</div></div></section>

      <section className="border-y border-[#D9E2E0] bg-[#E8F0EC] px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[90rem]"><OakHeading label="Resources" title="Helpful Property Management Guides" /><div className="mt-12 grid gap-5 md:grid-cols-3">{[['Owner expectations', 'What Landlords Should Expect from Property Management', 'A practical overview of communication, maintenance coordination, reporting, leasing support, and the boundaries set by a management agreement.'], ['Maintenance process', 'How Maintenance Requests Are Usually Handled', 'What happens after an issue is reported, from initial review and vendor assignment through updates and follow-up.'], ['Better communication', 'Clear Communication Tips for Tenants and Owners', 'Simple ways to share useful details, set expectations, document updates, and keep property conversations productive.']].map(([tag, title, text]) => <article key={title} className="oak-card rounded-[1.5rem] border border-white bg-white p-7"><p className="text-[0.62rem] font-black uppercase tracking-[0.18em] text-[#8FA377]">{tag}</p><h3 className="mt-4 text-2xl font-black leading-tight tracking-[-0.04em] text-[#16324A]">{title}</h3><p className="mt-4 text-sm leading-7 text-[#68787E]">{text}</p><a href="#contact" className="mt-6 inline-flex items-center gap-2 text-sm font-black text-[#3D7657]">Read Guide <ArrowRight className="h-4 w-4" /></a></article>)}</div></div></section>

      <section id="contact" className="relative bg-[#16324A] px-5 py-28 text-white lg:px-10 lg:py-36"><img src={ctaImage} alt="Well-managed Oakline residential property" className="absolute inset-0 h-full w-full object-cover opacity-22" /><div className="absolute inset-0 bg-gradient-to-r from-[#16324A] via-[#16324A]/92 to-[#16324A]/50" /><div className="relative mx-auto max-w-[90rem]"><div className="max-w-4xl"><p className="text-[0.66rem] font-black uppercase tracking-[0.24em] text-[#AFC39A]">Let’s simplify the day to day</p><h2 className="mt-5 text-[clamp(3rem,6.8vw,6.5rem)] font-black leading-[0.9] tracking-[-0.065em]">Ready for More Organized Property Management?</h2><p className="mt-7 max-w-2xl text-lg leading-8 text-white/68">Connect with Oakline Property Management to discuss landlord support, tenant communication, maintenance coordination, and transparent operations.</p><OakButton href="mailto:hello@oaklinepm.com" className="mt-9">Request Management Support</OakButton></div></div></section>

      <footer className="bg-[#10283B] px-5 pb-8 pt-16 text-white lg:px-10"><div className="mx-auto max-w-[90rem]"><div className="grid gap-10 border-b border-white/10 pb-12 md:grid-cols-2 lg:grid-cols-[1.35fr_.65fr_.8fr_1fr]"><div><OakLogo light /><p className="mt-6 max-w-sm text-sm leading-7 text-white/45">Property management for landlords and tenants with responsive service and transparent operations.</p></div><div><p className="font-black">Quick links</p><div className="mt-5 grid gap-3 text-sm text-white/45">{navLinks.slice(0, 4).map(([label, href]) => <a key={label} href={href} className="hover:text-white">{label}</a>)}</div></div><div><p className="font-black">Services</p><div className="mt-5 grid gap-3 text-sm text-white/45"><a href="#services">Rent Support</a><a href="#maintenance">Maintenance</a><a href="#services">Leasing Support</a><a href="#services">Owner Reporting</a></div></div><div><p className="font-black">Contact</p><div className="mt-5 grid gap-3 text-sm text-white/45"><a href="mailto:hello@oaklinepm.com">hello@oaklinepm.com</a><a href="tel:2125550126">(212) 555-0126</a><span>New York, NY</span></div></div></div><div className="flex flex-col gap-3 pt-7 text-[0.67rem] text-white/30 md:flex-row md:justify-between"><p>© 2026 Oakline Property Management. All rights reserved.</p><p>Services, response times, pricing, and availability may vary by property and management agreement.</p></div></div></footer>
    </main>
  )
}
