import { useEffect, useState, type ReactNode } from 'react'
import { ArrowRight, BarChart3, Check, ChevronUp, ClipboardCheck, Dumbbell, Hammer, Menu, MoveUpRight, ShieldCheck, Target, Weight, X, Zap } from 'lucide-react'
import heroImage from '../../assets/images/fitness/IronDistrict/hero.png'
import powerliftingImage from '../../assets/images/fitness/IronDistrict/powerlifting.png'
import foundationsImage from '../../assets/images/fitness/IronDistrict/strength-foundations.png'
import athleticImage from '../../assets/images/fitness/IronDistrict/athletic-performance.png'
import openGymImage from '../../assets/images/fitness/IronDistrict/open-gym.png'
import facilityImage from '../../assets/images/fitness/IronDistrict/facility.png'
import coachingImage from '../../assets/images/fitness/IronDistrict/coaching.png'
import formImage from '../../assets/images/fitness/IronDistrict/form-check.png'
import programmingImage from '../../assets/images/fitness/IronDistrict/strength-programming.png'
import groupImage from '../../assets/images/fitness/IronDistrict/small-group-training.png'
import membershipImage from '../../assets/images/fitness/IronDistrict/membershitp.png'
import cultureImage from '../../assets/images/fitness/IronDistrict/culture.png'
import abstractImage from '../../assets/images/fitness/IronDistrict/iron-abstract-bg.png'
import ctaImage from '../../assets/images/fitness/IronDistrict/cta.png'

const navLinks = [['Training', '#training'], ['Facility', '#facility'], ['Coaching', '#coaching'], ['Membership', '#membership'], ['Contact', '#contact']]

const programs = [
  { image: powerliftingImage, number: '01', title: 'Powerlifting', text: 'Squat, bench, and deadlift training built around technique, progression, and measurable strength.' },
  { image: foundationsImage, number: '02', title: 'Strength Foundations', text: 'Learn proper form, build confidence under the bar, and train with structure.' },
  { image: athleticImage, number: '03', title: 'Athletic Performance', text: 'Develop explosive power, conditioning, and durability for sport and everyday performance.' },
  { image: openGymImage, number: '04', title: 'Open Gym', text: 'Train independently with serious equipment, strong community standards, and no distractions.' },
]

const coaching = [
  { image: formImage, number: '01', title: 'Form Check Sessions', text: 'Get expert feedback on technique, setup, bracing, and movement quality.' },
  { image: programmingImage, number: '02', title: 'Strength Programming', text: 'Follow structured plans designed around progression, recovery, and consistency.' },
  { image: groupImage, number: '03', title: 'Small Group Training', text: 'Train with focused instruction, accountability, and a serious lifting community.' },
]

const memberships = [
  { name: 'Basic Iron', price: '$69', text: 'For independent lifters who need access to serious equipment.', features: ['Open gym access', 'Strength zones', 'Locker access'], popular: false },
  { name: 'District Strength', price: '$119', text: 'For members who want structure and coaching support.', features: ['Open gym access', 'Monthly form check', 'Program guidance'], popular: true },
  { name: 'Elite Barbell', price: '$229', text: 'For serious lifters who want full performance programming.', features: ['Custom strength plan', 'Weekly coaching', 'Priority platform access'], popular: false },
]

function IronButton({ href, children, outline = false, className = '' }: { href: string; children: ReactNode; outline?: boolean; className?: string }) {
  return <a href={href} className={`group inline-flex min-h-12 items-center justify-center gap-3 px-6 text-xs font-black uppercase tracking-[0.16em] transition duration-300 hover:-translate-y-0.5 ${outline ? 'border border-white/25 bg-white/[0.03] text-white hover:border-[#F6C945] hover:text-[#F6C945]' : 'bg-[#F6C945] text-[#0A0B0D] shadow-[7px_7px_0_rgba(255,255,255,.1)] hover:bg-[#ffda62]'} ${className}`}>{children}<ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></a>
}

function IronHeading({ label, title, text, light = false }: { label: string; title: string; text?: string; light?: boolean }) {
  return <div className="max-w-4xl"><p className="flex items-center gap-3 text-[0.62rem] font-black uppercase tracking-[0.25em] text-[#D89A2B] before:h-1 before:w-9 before:bg-[#F6C945]">{label}</p><h2 className={`mt-5 text-[clamp(3.2rem,6vw,6.5rem)] font-black uppercase leading-[0.82] tracking-[-0.075em] ${light ? 'text-white' : 'text-[#111318]'}`}>{title}</h2>{text && <p className={`mt-6 max-w-2xl text-base leading-8 md:text-lg ${light ? 'text-white/52' : 'text-[#646970]'}`}>{text}</p>}</div>
}

function IronLogo() {
  return <a href="#home" className="flex items-center gap-3 text-white" aria-label="IronDistrict Gym home"><span className="relative grid h-11 w-11 place-items-center border-2 border-[#F6C945] text-[#F6C945]"><Weight className="h-5 w-5" /><span className="absolute -bottom-1 -right-1 h-2.5 w-2.5 bg-[#F6C945]" /></span><span><strong className="block text-base font-black uppercase leading-none tracking-[-0.02em]">IronDistrict</strong><span className="mt-1 block text-[0.5rem] font-black uppercase tracking-[0.26em] text-white/38">Strength Facility</span></span></a>
}

export function IronDistrictGym() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [activeSection, setActiveSection] = useState('')

  useEffect(() => {
    const sections = navLinks.map(([, href]) => document.getElementById(href.slice(1))).filter((section): section is HTMLElement => section !== null)
    const observer = new IntersectionObserver((entries) => { const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0]; if (visible) setActiveSection(visible.target.id) }, { rootMargin: '-25% 0px -58% 0px', threshold: [0.05, 0.2, 0.5] })
    sections.forEach((section) => observer.observe(section))
    return () => observer.disconnect()
  }, [])

  return (
    <main className="irondistrict-site -mt-16 overflow-hidden bg-[#C9CDD1] text-[#111318] selection:bg-[#F6C945] selection:text-[#0A0B0D]">
      <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#0A0B0D]/95 text-white backdrop-blur-xl"><div className="mx-auto flex h-[4.75rem] max-w-[96rem] items-center justify-between px-5 lg:px-10"><IronLogo /><nav className="hidden items-center gap-1 lg:flex" aria-label="IronDistrict navigation">{navLinks.map(([label, href]) => { const active = activeSection === href.slice(1); return <a key={label} href={href} aria-current={active ? 'location' : undefined} className={`px-4 py-2 text-[0.64rem] font-black uppercase tracking-[0.14em] transition ${active ? 'irondistrict-nav-active bg-[#F6C945] text-[#0A0B0D]' : 'text-white/50 hover:bg-white/[0.06] hover:text-white'}`}>{label}</a> })}</nav><IronButton href="#contact" className="hidden lg:inline-flex">Join The District</IronButton><button type="button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation" aria-expanded={menuOpen} className="grid h-10 w-10 place-items-center border border-white/15 lg:hidden">{menuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div>{menuOpen && <nav className="border-t border-white/10 bg-[#0A0B0D] p-5 lg:hidden">{navLinks.map(([label, href]) => { const active = activeSection === href.slice(1); return <a key={label} href={href} aria-current={active ? 'location' : undefined} onClick={() => setMenuOpen(false)} className={`block px-4 py-3 text-sm font-black uppercase tracking-[0.1em] ${active ? 'irondistrict-nav-active bg-[#F6C945] text-[#0A0B0D]' : 'text-white/58'}`}>{label}</a> })}<IronButton href="#contact" className="mt-4 w-full">Join The District</IronButton></nav>}</header>

      <section id="home" className="relative bg-[#C9CDD1] pt-[4.75rem] text-[#0A0B0D]">
        <img src={abstractImage} alt="" className="absolute inset-0 h-full w-full object-cover opacity-[0.08] mix-blend-multiply" />
        <div className="relative mx-auto grid min-h-[54rem] max-w-[100rem] border-x border-[#777D83] lg:grid-cols-[1.05fr_.95fr]">
          <div className="flex flex-col justify-between border-b border-[#777D83] p-5 pt-14 lg:border-b-0 lg:border-r lg:p-10 lg:pt-16 xl:p-16">
            <div className="flex items-center justify-between gap-4 border-b border-[#777D83] pb-5"><p className="text-[0.62rem] font-black uppercase tracking-[0.22em]">IronDistrict / Strength Facility</p><span className="bg-[#F6C945] px-3 py-2 text-[0.58rem] font-black uppercase tracking-[0.14em]">Est. 2018</span></div>
            <div className="py-14"><p className="flex items-center gap-3 text-[0.62rem] font-black uppercase tracking-[0.22em]"><span className="h-3 w-3 bg-[#0A0B0D]" /> Hardcore strength training</p><h1 className="mt-7 max-w-4xl text-[clamp(4.8rem,8.8vw,9.2rem)] font-black uppercase leading-[0.68] tracking-[-0.095em]">Built for <span className="inline-block bg-[#0A0B0D] px-3 text-[#F6C945]">heavy</span> days and hard work.</h1><p className="mt-8 max-w-xl text-lg font-semibold leading-8 text-[#444A50]">Elite equipment, serious coaching, and a focused environment for lifters who train with purpose.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><IronButton href="#contact">Start Training</IronButton><a href="#membership" className="inline-flex min-h-12 items-center justify-center gap-3 border border-[#0A0B0D] px-6 text-xs font-black uppercase tracking-[0.16em] transition hover:bg-[#0A0B0D] hover:text-white">View Memberships <ArrowRight className="h-4 w-4" /></a></div></div>
            <div className="grid grid-cols-2 border-l border-t border-[#777D83] sm:grid-cols-4">{[['24', 'Strength Stations'], ['COMP', 'Powerlifting Ready'], ['COACH', 'Led Programs'], ['OPEN', 'Gym Access']].map(([value, label]) => <div key={label} className="border-b border-r border-[#777D83] p-4"><p className="text-2xl font-black">{value}</p><p className="mt-1 text-[0.5rem] font-black uppercase tracking-[0.15em] text-[#555B61]">{label}</p></div>)}</div>
          </div>
          <div className="relative min-h-[42rem] overflow-hidden bg-[#0A0B0D] p-4 lg:min-h-full lg:p-7">
            <img src={heroImage} alt="Heavy strength training inside IronDistrict Gym" className="h-full min-h-[40rem] w-full object-cover grayscale-[35%] contrast-125" />
            <div className="absolute inset-x-4 bottom-4 grid grid-cols-[1fr_auto] items-end bg-[#0A0B0D]/90 p-5 text-white backdrop-blur lg:inset-x-7 lg:bottom-7"><div><p className="text-[0.58rem] font-black uppercase tracking-[0.2em] text-[#F6C945]">Floor status / Active</p><p className="mt-2 text-3xl font-black uppercase leading-none">No mirrors. No posing. Just work.</p></div><ChevronUp className="h-7 w-7 text-[#F6C945]" /></div>
            <div className="absolute right-0 top-20 bg-[#F6C945] px-3 py-8 text-[0.6rem] font-black uppercase tracking-[0.16em] [writing-mode:vertical-rl]">District Standard</div>
          </div>
        </div>
      </section>

      <section id="training" className="bg-[#E1E3E5] px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[96rem]"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><IronHeading label="Training programs" title="Strength training with purpose" text="Every lane is built around deliberate work, quality reps, and progression you can explain." /><p className="max-w-xl border-l-4 border-[#F6C945] pl-5 text-sm leading-7 text-[#555B62]">Four training lanes. One rule: every session should have a reason.</p></div><div className="mt-14 border-y-2 border-[#0A0B0D]">{programs.map((program) => <article key={program.title} className="group grid gap-5 border-b border-[#8D9297] py-5 last:border-b-0 md:grid-cols-[4rem_.7fr_1fr_13rem_auto] md:items-center"><span className="text-3xl font-black text-[#8C7200]">{program.number}</span><h3 className="text-3xl font-black uppercase leading-none tracking-[-0.055em]">{program.title}</h3><p className="text-sm leading-7 text-[#555B62]">{program.text}</p><div className="relative hidden aspect-[16/9] overflow-hidden md:block"><img src={program.image} alt={`${program.title} training`} className="h-full w-full object-cover grayscale transition duration-500 group-hover:scale-105 group-hover:grayscale-0" /></div><a href="#contact" aria-label={`Explore ${program.title}`} className="grid h-12 w-12 place-items-center border border-[#0A0B0D] transition group-hover:bg-[#F6C945]"><MoveUpRight className="h-5 w-5" /></a></article>)}</div></div></section>

      <section id="facility" className="bg-[#111318] px-5 py-24 text-white lg:px-10 lg:py-32"><div className="mx-auto grid max-w-[96rem] gap-12 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div className="relative"><img src={facilityImage} alt="IronDistrict heavy racks and lifting platforms" className="min-h-[44rem] w-full object-cover grayscale-[20%]" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#0A0B0D] to-transparent p-7 pt-28"><p className="text-[0.6rem] font-black uppercase tracking-[0.2em] text-[#F6C945]">The training floor</p><p className="mt-2 text-3xl font-black uppercase">Built to work. Kept in order.</p></div></div><div><IronHeading label="Facility" title="A facility built for serious lifters" text="Heavy racks and platforms, competition-grade barbells, dumbbells, machines, sleds, conditioning tools, and chalk-friendly zones—organized for focused work." light /><div className="mt-9 grid gap-3 sm:grid-cols-2">{[[Weight, 'Heavy Platforms'], [Hammer, 'Steel Racks'], [ClipboardCheck, 'Coach Support'], [Zap, 'Focused Atmosphere']].map(([Icon, title]) => { const FeatureIcon = Icon as typeof Weight; return <div key={title as string} className="border border-white/12 bg-white/[0.045] p-5"><FeatureIcon className="h-5 w-5 text-[#F6C945]" /><p className="mt-6 text-sm font-black uppercase tracking-[0.08em]">{title as string}</p></div> })}</div></div></div></section>

      <section id="coaching" className="bg-[#E1E3E5] px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[96rem]"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><IronHeading label="Strength coaching" title="Coaching that keeps your training honest" text="Clear eyes on technique, programming that earns progression, and accountability that respects the work." /><img src={coachingImage} alt="IronDistrict coach supporting a strength session" className="hidden h-64 w-full object-cover grayscale lg:block" /></div><div className="mt-12 grid gap-4 lg:grid-cols-3">{coaching.map((item) => <article key={item.title} className="iron-card group overflow-hidden border border-[#AEB3B8] bg-[#C9CDD1]"><div className="relative aspect-[16/10] overflow-hidden"><img src={item.image} alt={item.title} className="h-full w-full object-cover grayscale transition duration-700 group-hover:scale-105 group-hover:grayscale-0" /><span className="absolute right-4 top-4 text-5xl font-black text-white/38">{item.number}</span></div><div className="p-7"><h3 className="text-3xl font-black uppercase leading-none tracking-[-0.05em]">{item.title}</h3><p className="mt-4 text-sm leading-7 text-[#555B62]">{item.text}</p></div></article>)}</div></div></section>

      <section id="membership" className="relative bg-[#0A0B0D] px-5 py-24 text-white lg:px-10 lg:py-32"><img src={membershipImage} alt="" className="absolute inset-0 h-full w-full object-cover opacity-[0.07] grayscale" /><div className="relative mx-auto max-w-[96rem]"><IronHeading label="Membership" title="Pay for access. Earn the progress." text="Three levels of support for lifters who know how they want to work. Pricing and access may vary by schedule and location." light /><div className="mt-14 grid gap-4 lg:grid-cols-3">{memberships.map((plan) => <article key={plan.name} className={`relative flex flex-col border p-7 ${plan.popular ? 'border-[#F6C945] bg-[#F6C945] text-[#0A0B0D] shadow-[12px_12px_0_rgba(255,255,255,.12)] lg:-translate-y-4' : 'border-white/15 bg-[#17191D]'}`}>{plan.popular && <span className="absolute right-5 top-5 bg-[#0A0B0D] px-3 py-2 text-[0.58rem] font-black uppercase tracking-[0.14em] text-[#F6C945]">Most Popular</span>}<p className={`text-[0.6rem] font-black uppercase tracking-[0.18em] ${plan.popular ? 'text-[#5A4700]' : 'text-[#F6C945]'}`}>District membership</p><h3 className="mt-6 text-4xl font-black uppercase leading-none tracking-[-0.06em]">{plan.name}</h3><div className="mt-8 flex items-end gap-2"><span className="text-6xl font-black tracking-[-0.08em]">{plan.price}</span><span className={`pb-2 text-xs font-bold ${plan.popular ? 'text-black/50' : 'text-white/35'}`}>/ month</span></div><p className={`mt-5 text-sm leading-7 ${plan.popular ? 'text-black/62' : 'text-white/48'}`}>{plan.text}</p><div className={`mt-6 grid gap-3 border-t pt-6 ${plan.popular ? 'border-black/20' : 'border-white/12'}`}>{plan.features.map((feature) => <span key={feature} className="flex items-center gap-2 text-sm font-bold"><Check className={`h-4 w-4 ${plan.popular ? 'text-black' : 'text-[#F6C945]'}`} />{feature}</span>)}</div><a href="#contact" className={`mt-8 inline-flex min-h-12 items-center justify-center px-5 text-xs font-black uppercase tracking-[0.14em] transition ${plan.popular ? 'bg-[#0A0B0D] text-white hover:bg-[#25282D]' : 'bg-[#F6C945] text-[#0A0B0D] hover:bg-[#ffda62]'}`}>Choose {plan.name}</a></article>)}</div></div></section>

      <section className="relative bg-[#23262B] px-5 py-24 text-white lg:px-10 lg:py-32"><img src={cultureImage} alt="IronDistrict members training in a focused environment" className="absolute inset-0 h-full w-full object-cover opacity-25 grayscale" /><div className="absolute inset-0 bg-gradient-to-r from-[#111318] via-[#111318]/92 to-[#111318]/55" /><div className="relative mx-auto max-w-[96rem]"><IronHeading label="Results & culture" title="No hype. Just work." text="IronDistrict is built for consistency, discipline, and measurable progress. Every rep has a reason. Every session has a purpose." light /><div className="mt-12 grid border-l border-t border-white/15 sm:grid-cols-2 lg:grid-cols-4">{[[Dumbbell, 'Stronger lifts'], [Target, 'Better technique'], [ShieldCheck, 'More discipline'], [BarChart3, 'Clearer programming']].map(([Icon, title], index) => { const CultureIcon = Icon as typeof Dumbbell; return <div key={title as string} className="border-b border-r border-white/15 bg-black/30 p-6"><span className="text-xs font-black text-[#F6C945]">0{index + 1}</span><CultureIcon className="mt-10 h-6 w-6 text-[#F6C945]" /><h3 className="mt-5 text-xl font-black uppercase">{title as string}</h3></div> })}</div></div></section>

      <section className="bg-[#C9CDD1] px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[96rem]"><IronHeading label="Member log" title="The room changes how you train" /><div className="mt-12 grid gap-4 md:grid-cols-3">{[['Marcus T.', 'My squat setup is more consistent now because the coaching is direct and specific. I know what to fix between sets.'], ['Jalen R.', 'The environment makes it easier to stick to a real routine. People come in ready to work, and that keeps me focused.'], ['Casey M.', 'I wanted serious equipment without the chaos. The floor is organized, the standards are clear, and training feels purposeful.']].map(([name, quote], index) => <blockquote key={name} className="border border-[#999FA5] bg-[#B9BEC3] p-7"><span className="text-5xl font-black text-[#8F7200]">“</span><p className="mt-4 text-lg font-semibold leading-8 text-[#292D32]">{quote}</p><footer className="mt-8 flex items-center gap-3 border-t border-[#969CA2] pt-5"><span className="grid h-10 w-10 place-items-center bg-[#111318] text-xs font-black text-[#F6C945]">0{index + 1}</span><div><p className="font-black uppercase">{name}</p><p className="text-xs text-[#62686E]">District member</p></div></footer></blockquote>)}</div></div></section>

      <section id="contact" className="relative bg-[#0A0B0D] px-5 py-28 text-white lg:px-10 lg:py-36"><img src={ctaImage} alt="IronDistrict strength training floor" className="absolute inset-0 h-full w-full object-cover opacity-35 grayscale-[25%]" /><div className="absolute inset-0 bg-gradient-to-r from-[#0A0B0D] via-[#0A0B0D]/90 to-[#0A0B0D]/35" /><div className="relative mx-auto max-w-[96rem]"><div className="max-w-5xl"><p className="text-[0.62rem] font-black uppercase tracking-[0.24em] text-[#F6C945]">The bar is loaded</p><h2 className="mt-6 text-[clamp(4rem,8vw,8.8rem)] font-black uppercase leading-[0.74] tracking-[-0.085em]">Step into the district.</h2><p className="mt-8 max-w-2xl text-lg leading-8 text-white/58">Join a gym built for heavy training, focused coaching, and members who take strength seriously.</p><IronButton href="mailto:join@irondistrict.example" className="mt-9">Join The Gym</IronButton></div></div></section>

      <footer className="border-t border-white/10 bg-[#07080A] px-5 pb-8 pt-14 text-white lg:px-10"><div className="mx-auto max-w-[96rem]"><div className="flex flex-col justify-between gap-10 border-b border-white/10 pb-10 lg:flex-row lg:items-start"><div><IronLogo /><p className="mt-5 max-w-sm text-sm leading-7 text-white/38">Hardcore strength training for serious lifters.</p></div><div className="flex flex-wrap gap-x-8 gap-y-4">{navLinks.map(([label, href]) => <a key={label} href={href} className="text-xs font-black uppercase tracking-[0.13em] text-white/40 hover:text-[#F6C945]">{label}</a>)}</div><div><p className="text-[0.58rem] font-black uppercase tracking-[0.18em] text-white/30">District social</p><div className="mt-4 flex gap-2">{['IG', 'YT', 'TK'].map((social) => <a key={social} href="#contact" aria-label={`${social} social placeholder`} className="grid h-10 w-10 place-items-center border border-white/15 text-[0.6rem] font-black hover:border-[#F6C945] hover:text-[#F6C945]">{social}</a>)}</div></div></div><p className="pt-7 text-[0.65rem] text-white/25">© 2026 IronDistrict Gym. Membership pricing, coaching schedules, facility access, and availability are subject to change.</p></div></footer>
    </main>
  )
}
