import { useState } from 'react'
import { ArrowRight, BarChart3, BookOpen, Brain, CalendarDays, Check, ChevronDown, CircleHelp, Clock3, FileText, GraduationCap, LineChart, Menu, MessageCircle, ShieldCheck, Sparkles, Star, Target, Users, X } from 'lucide-react'
import './ExamEdgePrep.css'

const programs = [
  ['SAT','SAT Prep','Duration: 12 Weeks','Build skills. Master strategies. Raise your score.','blue'],
  ['ACT','ACT Prep','Duration: 12 Weeks','Science timing, strategies—ACE the ACT.','aqua'],
  ['▦','Math Intensive','Duration: 6 Weeks','Deepen concepts. Boost accuracy & speed.','purple'],
  ['✎','Reading & Writing Boost','Duration: 6 Weeks','Stronger reading. Sharper writing. Higher scores.','orange'],
  ['🚀','Last-Minute Bootcamp','Duration: 2 Weeks','High-impact review for test day.','coral'],
]
const journey = [['1','Take Diagnostic','Full-length test to understand your starting point.'],['2','Review Score Report','Understand strengths, weaknesses, and opportunities.'],['3','Get Adaptive Plan','Your AI-powered plan builds around your target score.'],['4','Practice & Learn','Adaptive practice lessons and content that get results.'],['5','Meet Your Coach','Regular 1:1 or group sessions to keep you on track.'],['6','Test Day Ready','Go in confident. Do your best. Achieve more.']]
const coaches = [['Maya Patel','Head SAT Coach','150+ Score Increase','MP'],['Daniel Kim','ACT Specialist','ACT 36 Score','DK'],['Laura Bennett','Reading & Writing Coach','SAT Expert','LB'],['Arjun Mehta','Math Instructor','Perfect 800 Math','AM']]

export function ExamEdgePrep() {
  const [open, setOpen] = useState<number | null>(null)
  const [menuOpen, setMenuOpen] = useState(false)
  const go = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' })
  return <main className="ee-site">
    <header className="ee-nav"><a className="ee-logo" href="#top"><ShieldCheck/> <b>Exam<span>Edge</span></b><small>PREP</small></a><button className="ee-menu" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button><nav className={menuOpen?'open':''}>{['Programs','Diagnostic','Study Plans','Coaches','Results','Pricing','FAQ'].map(x=><button key={x} onClick={()=>{setMenuOpen(false);go(x.toLowerCase().replace(' ','-'))}}>{x}{x==='Programs'&&<ChevronDown/>}</button>)}<button className="ee-nav-cta" onClick={()=>go('pricing')}><CalendarDays/>Book a Free Diagnostic</button></nav></header>
    <section id="top" className="ee-hero ee-wrap"><div className="ee-hero-copy"><h1>Higher Scores.<br/>Stronger Futures.<em>We Raise SAT & ACT Scores.</em></h1><p>Start with a precision diagnostic. Get a personalized study plan, adaptive practice, and expert coaching that drives real score gains.</p><div className="ee-actions"><button onClick={()=>go('diagnostic')}>Start Your Free Diagnostic <ArrowRight/></button><button className="outline" onClick={()=>go('study-plans')}>See Study Plans</button></div><div className="ee-trust"><span><Check/> No credit card required</span><span><Check/> Personalized in minutes</span><span><Star/> Trusted by 10,000+ families</span></div></div><HeroDashboard/></section>
    <section className="ee-proof"><div className="ee-wrap">{[['👥','10,000+','Students Helped'],['↗','180+','Average SAT Point Increase'],['▤','3.2M+','Practice Questions Completed'],['☆','4.9/5','Student Satisfaction']].map(([icon,value,label])=><article key={label}><i>{icon}</i><b>{value}</b><small>{label}</small></article>)}</div></section>
    <section className="ee-wrap ee-section"><h2>Why ExamEdge Prep?</h2><div className="ee-why">{[[Target,'Full-Length Diagnostics','Official-style tests reveal accurate baselines.'],[FileText,'Personalized Study Plans','AI-powered plans built around your goals.'],[Brain,'Adaptive Practice','Smart practice that focuses on weaknesses.'],[Users,'Expert Coaching','Top 1% coaches. Real guidance. Real results.'],[CalendarDays,'Flexible Schedules','Live online sessions that fit your life.'],[BarChart3,'Score Tracking','Track progress. Stay motivated. Improve.']].map(([Icon,title,copy])=>{const I=Icon as typeof Target;return <article key={String(title)}><I/><b>{title as string}</b><p>{copy as string}</p></article>})}</div></section>
    <section id="programs" className="ee-wrap ee-section"><h2>Our Programs</h2><div className="ee-programs">{programs.map(([icon,title,duration,copy,color])=><article key={title}><i className={color}>{icon}</i><h3>{title}</h3><small>{duration}</small><ul><li><Check/> Personalized Study Plan</li><li><Check/> Format: Live Online</li><li><Check/> Ideal For: 9th–12th Grade</li></ul><p>{copy}</p><button onClick={()=>go('pricing')}>Explore Program <ArrowRight/></button></article>)}</div></section>
    <section id="study-plans" className="ee-wrap ee-section"><h2>Your Learning Journey</h2><div className="ee-journey">{journey.map(([number,title,copy])=><article key={number}><b>{number}</b><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section id="diagnostic" className="ee-wrap ee-section"><h2>Sample Weekly Study Schedule</h2><div className="ee-schedule"><div>{['Time','Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=><b key={x}>{x}</b>)}</div>{[['7:00 – 8:00 PM','Math Practice','Reading Practice','Math Practice','Grammar Practice','Math Practice','Full-Length Section','Rest & Review'],['4:30 – 5:30 PM','Lesson: Algebra II','Lesson: Reading','Lesson: Geometry','Lesson: Writing','Lesson: Data Analysis','Mock Test','Review Mistakes'],['6:00 – 7:00 PM','▣ Coach Call','◉ Adaptive Drill','▣ Coach Call','◉ Adaptive Drill','▣ Coach Call','Results Review','Plan Next Week'],['7:30 – 8:00 PM','Flashcards','Vocabulary','Flashcards','Vocabulary','Flashcards','Exam Strategies','Light Study']].map((row,i)=><div key={i}>{row.map(cell=><span key={cell}>{cell}</span>)}</div>)}</div></section>
    <section id="coaches" className="ee-wrap ee-section"><h2>Meet Our Expert Coaches</h2><div className="ee-coaches">{coaches.map(([name,role,result,initials],i)=><article key={name}><i className={`coach-${i}`}>{initials}</i><div><b>{name}</b><span>{role}</span><p>• 10+ Years Experience<br/>• Harvard University<br/>• {result}</p><button>View Profile <ArrowRight/></button></div></article>)}</div></section>
    <section id="results" className="ee-wrap ee-section"><h2>Results That Speak</h2><div className="ee-results"><article><small>Average SAT Score Increase</small><b>+180</b><span>Points</span><div className="ee-line"><i/><i/><i/></div></article><article><small>Average ACT Score Increase</small><b>+4.6</b><span>Points</span><div className="ee-bars"><i/><i/></div></article><article><small>Practice Completion Rate</small><strong>87%<span>SAT Target</span></strong><p><Check/> Lessons <Check/> Practice Drills</p></article><article><small>College Admissions Confidence</small><strong>94%<span>More Confident</span></strong><p>Students feel more prepared and confident after our program.</p></article></div></section>
    <section className="ee-wrap ee-section"><h2>Inside Your Student Dashboard</h2><div className="ee-stories">{[['RS','“My SAT score increased by 210 points! The coaching and study plan were game-changers for me.”','Rohan S.'],['AN','“The ACT strategies and practice tests helped me improve my score by 5 points. Highly recommend!”','Amaya K.'],['DP','“Excellent program, fantastic coaches, and real results. My daughter gained confidence!”','Parent of Diya P.']].map(([initials,quote,name])=><article key={name}><i>{initials}</i><p>{quote}</p><b>— {name}</b><span>★★★★★</span></article>)}</div></section>
    <section id="pricing" className="ee-wrap ee-section"><h2>Simple, Transparent Pricing</h2><div className="ee-pricing">{([['Starter','$299','Build the foundation.',['Full-Length Diagnostic','Personalized Study Plan','Adaptive Practice','Email Support']],['Guided Prep','$499','Structured. Supported. Successful.',['Everything in Starter','Weekly Live Coach Sessions','Mock Tests & Reviews','Priority Support']],['Elite Coaching','$999','Personalized. Premium. Results.',['Everything in Guided Prep','1:1 Coaching (Weekly)','Custom Strategy Plan','Unlimited Support']]] as [string, string, string, string[]][]).map(([name,price,tag,features],i)=><article key={name} className={i===1?'popular':''}>{i===1&&<small className="ee-popular">Most Popular</small>}<h3>{name}</h3><p>{tag}</p><b>{price}<small>/ month</small></b><ul>{features.map(f=><li key={f}><Check/>{f}</li>)}</ul><button onClick={()=>alert(`${name} selected`)}>Get Started</button></article>)}</div></section>
    <section id="faq" className="ee-wrap ee-section"><h2>Frequently Asked Questions</h2><div className="ee-faq">{['What tests do you prepare for?','How does the diagnostic work?','How long are the programs?','How are study plans personalized?','Do you offer 1:1 coaching?','What if I’m not satisfied?'].map((question,i)=><article key={question}><button onClick={()=>setOpen(open===i?null:i)}>{question}<span>{open===i?'−':'+'}</span></button>{open===i&&<p>We tailor guidance, practice, and support around your goals so you always know the next best step.</p>}</article>)}</div></section>
    <section className="ee-cta"><div className="ee-wrap"><i>🎓</i><div><h2>Ready to Raise Your Score?</h2><p>Book your free diagnostic today and take the first step toward your dream college.</p></div><button onClick={()=>go('diagnostic')}><CalendarDays/>Book Your Free Diagnostic</button></div></section>
    <footer className="ee-footer"><div className="ee-wrap"><div><a className="ee-logo" href="#top"><ShieldCheck/><b>Exam<span>Edge</span></b><small>PREP</small></a><p>Smarter preparation.<br/>Stronger scores.<br/>Brighter futures.</p><span>f　◎　▶　in</span></div><Footer title="Quick Links" items={['Programs','Diagnostic','Study Plans','Coaches','Results','Pricing','FAQ']}/><Footer title="Resources" items={['SAT Tips','ACT Tips','Practice Questions','Study Guides','Blog','Students','Parents']}/><Footer title="Company" items={['About Us','Our Coaches','Success Stories','Careers','Contact Us']}/><div><h3>Contact Us</h3><p>☎ (888) 123-EDGE<br/>✉ hello@examedgeprep.com<br/>⌖ 400 Education Way, Suite 200<br/>Austin, TX 78701</p></div><div><h3>Newsletter</h3><p>Get tips, strategies, and exclusive offers.</p><input placeholder="Enter your email"/><button>Subscribe</button></div></div><small className="ee-copy">© 2024 ExamEdge Prep. All rights reserved.</small></footer>
  </main>
}
function Footer({title,items}:{title:string;items:string[]}){return <div><h3>{title}</h3>{items.map(i=><a href="#top" key={i}>{i}</a>)}</div>}
function HeroDashboard(){return <div className="ee-dashboard"><article><small>Diagnostic Score Summary</small><div className="ee-scores"><b>SAT <strong>1310</strong><span>Total Score</span></b><b>ACT <strong>29</strong><span>Composite</span></b></div><p>Predicted Improvement <em>+210 to +280</em> SAT Points</p></article><article><small>Weekly Study Plan</small><b>Week 3 of 12 <em>75%</em></b><i className="ee-progress"><span/></i>{['Algebra II','Reading Comprehension','Grammar & Usage','Full-Length Practice'].map((x,i)=><p key={x}><Check className={i>1?'muted':''}/>{x}<span>{i<2?'4/5':'3/5'}</span></p>)}</article><article className="ee-chart"><small>Score Progress</small><span>● SAT Score　● ACT Score</span><svg viewBox="0 0 300 120" aria-label="Score progress chart"><path d="M5 105 L60 92 L120 82 L175 64 L230 24 L292 18"/><path d="M5 112 L60 109 L120 103 L175 89 L230 78 L292 62"/></svg></article><article className="ee-session"><small>Upcoming Coaching</small><i>MP</i><b>Strategy Session</b><p>Today, 6:00 PM<br/>with Coach Maya</p><button>Join Session</button></article></div>}
