import { useState } from 'react'
import { ArrowRight, Award, BookOpen, CalendarDays, Check, ChevronDown, Clock3, Globe2, GraduationCap, HeartHandshake, Menu, MessageCircle, Sparkles, Star, Users, X } from 'lucide-react'
import './FluentPathLanguages.css'

const programs = [['English for Professionals','A2–C1','🗂️','Build confidence for meetings, emails, and work.'],['Spanish for Travel & Life','A1–B2','🏛️','Speak naturally for travel and daily life.'],['French for Communication','A1–B2','🗼','Connect, converse, and feel at home.'],['Arabic Foundations','A1–B1','⌘','Learn essential language and culture.'],['German for Work','A1–B2','🏰','Practical German for your career.'],['IELTS & Business English','A1–C1','💼','Reach your next professional goal.']]
const road = [['1','Foundations','Build core vocabulary, pronunciation, and basic grammar.'],['2','Core Grammar','Strengthen grammar structures and sentence patterns.'],['3','Listening & Speaking','Develop listening skills and start speaking naturally.'],['4','Real-Life Conversation','Practice in real scenarios with instructor feedback.'],['5','Writing & Reading','Improve reading comprehension and clear writing.'],['6','Final Fluency Project','Apply your skills in a real-world project.']]
const instructors = [['Daniela Ruiz','Spanish Specialist','DR'],['Michael Chen','English Specialist','MC'],['Leila Haddad','Arabic Specialist','LH'],['Jean-Baptiste Lefèvre','French Specialist','JL']]

export function FluentPathLanguages(){const [menu,setMenu]=useState(false);const [faq,setFaq]=useState<number|null>(null);const go=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});return <main className="fl-site">
<header className="fl-nav"><a className="fl-logo" href="#top"><Globe2/><b>FluentPath</b><small>Languages</small></a><button className="fl-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav className={menu?'open':''}>{['Programs','Method','Instructors','Schedule','Outcomes','Pricing','FAQ'].map(x=><button key={x} onClick={()=>{setMenu(false);go(x.toLowerCase())}}>{x}{x==='Programs'&&<ChevronDown/>}</button>)}<button className="fl-call" onClick={()=>go('pricing')}>Book a Placement Call</button></nav></header>
<section id="top" className="fl-hero fl-wrap"><div><h1>Language learning<br/>for adults who want<br/><em>real progress.</em></h1><p>Structured courses, live instructors, and conversation practice designed for real life—so you can speak with confidence at work, while traveling, and in everyday moments.</p><div className="fl-actions"><button onClick={()=>go('programs')}>Explore Courses <ArrowRight/></button><button className="outline" onClick={()=>go('method')}>▧ Take a Placement Quiz</button></div><div className="fl-mini"><span><Users/> Small Cohorts</span><span><MessageCircle/> Live Lessons</span><span><CalendarDays/> Flexible Schedule</span><span><Award/> CEFR-aligned</span></div></div><HeroCards/></section>
<section className="fl-proof"><div className="fl-wrap">{[['♧','15,000+','Adult Learners'],['◉','92%','Course Completion Rate'],['☆','4.8/5','Learner Satisfaction'],['◎','30+','Countries Represented'],['☏','8','Languages Offered']].map(([i,b,s])=><article key={s}><i>{i}</i><b>{b}</b><small>{s}</small></article>)}</div></section>
<section className="fl-wrap fl-section"><h2>Why FluentPath Languages?</h2><div className="fl-why">{[[GraduationCap,'Structured Pathways','Clear progression from foundations to fluency with CEFR-aligned learning paths.'],[Users,'Native-Level Instructors','Experienced, certified instructors who guide, challenge, and support your growth.'],[MessageCircle,'Conversation Practice','Real conversations, role plays, and feedback to help you speak confidently.'],[Clock3,'Flexible Evening Classes','Designed for busy adults with live classes in the evenings and weekends.'],[Globe2,'Career & Travel Focus','Practical language for workplace success and travels that connect you to the world.'],[HeartHandshake,'Supportive Community','Small cohorts and community events that keep you motivated and engaged.']].map(([Icon,t,p])=>{const I=Icon as typeof Users;return <article key={String(t)}><I/><b>{t as string}</b><p>{p as string}</p></article>})}</div></section>
<section id="programs" className="fl-wrap fl-section"><h2>Our Programs</h2><p className="fl-sub">Choose a program that fits your goals. All courses are live, interactive, and outcomes-driven.</p><div className="fl-programs">{programs.map(([name,level,icon,copy])=><article key={name}><div className="fl-placeholder"><span>{icon}</span></div><h3>{name}</h3><small>Levels: {level}<br/>Format: Live Online<br/>Duration: 8–12 weeks</small><p>{copy}</p><button onClick={()=>go('pricing')}>Learn More <ArrowRight/></button></article>)}</div></section>
<section id="method" className="fl-wrap fl-section"><h2>Our Curriculum Roadmap</h2><p className="fl-sub">A proven learning journey that builds confidence, competence, and fluency.</p><div className="fl-road">{road.map(([n,t,p])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{p}</p><small>{n==='1'?'Completed':n==='2'?'In Progress':n==='6'?'Final Stage':'Upcoming'}</small></article>)}</div></section>
<section id="schedule" className="fl-wrap fl-section"><h2>Weekly Schedule</h2><p className="fl-sub">Evening classes, intensives and clubs on weekends.</p><Schedule/></section>
<section id="instructors" className="fl-wrap fl-section"><h2>Learn from Expert Instructors</h2><p className="fl-sub">Experienced educators. Global perspectives. Personalized support.</p><div className="fl-instructors">{instructors.map(([name,role,initial],i)=><article key={name}><div className={`fl-person p${i}`}>{initial}</div><b>{name}</b><span>{role}</span><p>🇪🇸 Spanish<br/>◷ 10+ years experience<br/>◎ M.A. Applied Linguistics</p></article>)}<aside><b>Quality You Can Trust</b><p>◉ Rigorous instructor screening & training</p><p>◉ Continuous feedback & observation</p><p>◉ Personalized coaching for your growth</p><strong>★★★★★　4.8/5</strong></aside></div></section>
<section id="outcomes" className="fl-wrap fl-section"><h2>Real Results. Real Confidence.</h2><div className="fl-results"><article><strong>89%</strong><p>of learners improved their speaking confidence</p><small>After 12 weeks with FluentPath</small></article><article><b>1.3</b><p>CEFR Progression<br/>Average level improvement</p><div className="fl-bars"><i/><i/><i/><i/></div></article><article><p>Skills Growth<br/>Average improvement across key skills</p>{['Speaking 92%','Listening 87%','Reading 82%','Writing 76%'].map(x=><span key={x}>{x}<i/></span>)}</article><article><b>You’ll Achieve</b><p>✓ Confident conversations in real life<br/>✓ Interview & presentation readiness<br/>✓ Travel and cultural confidence<br/>✓ Workplace communication</p></article></div></section>
<section className="fl-wrap fl-section"><h2>Your Learning Journey</h2><p className="fl-sub">Simple steps to start your path to fluency.</p><div className="fl-journey">{['Choose Your Language','Take the Placement Quiz','Meet Your Learning Advisor','Join Your Cohort','Attend Live Classes','Reach Your Fluency Goals'].map((x,i)=><article key={x}><i>{[Globe2,FileIcon,Users,Users,BookOpen,Award].map((C,j)=>j===i?<C key={j}/>:null)}</i><b>{i+1}</b><h3>{x}</h3><p>{i===0?'Pick a program that matches your goals.':'Get a personalized recommendation and start.'}</p></article>)}</div></section>
<section className="fl-wrap fl-section"><h2>What Our Learners Say</h2><div className="fl-quotes">{[['AP','“FluentPath helped me speak English confidently at work. The instructors are supportive and the classes are practical and engaging.”','Arjun Patel, Product Manager, India'],['SM','“I needed Spanish for my travels and everyday life in Spain. The conversation clubs made such a big difference!”','Sophie Martin, Marketing Specialist, France'],['OF','“The Arabic course was structured, yet flexible. I now communicate with my team and clients with clarity.”','Omar Al-Farsi, Entrepreneur, UAE']].map(([i,q,n])=><article key={n}><i>{i}</i><p>{q}</p><b>{n}</b><span>★★★★★</span></article>)}</div></section>
<section id="pricing" className="fl-wrap fl-section"><h2>Choose the Plan That Fits You</h2><div className="fl-pricing">{([['Essentials','$149','Perfect for building a strong foundation.',['2 Live Classes / Week','Access to Learning Platform','Office Hours','Community Events']],['Guided Cohort','$249','Best balance of learning and practice.',['3 Live Classes / Week','Conversation Labs','Office Hours + Feedback','Progress Tracking']],['Intensive','$399','Accelerated learning for fast results.',['5 Live Classes / Week','Weekend Intensives','1-on-1 Coaching Session','Priority Feedback']]] as [string, string, string, string[]][]).map(([n,p,t,fs],i)=><article key={n} className={i===1?'hot':''}>{i===1&&<small>Most Popular</small>}<h3>{n}</h3><p>{t}</p><b>{p}<em>/ month</em></b><ul>{fs.map(x=><li key={x}><Check/>{x}</li>)}</ul><button onClick={()=>alert(`${n} plan selected`)}>Get Started</button></article>)}<aside><i>🗺️</i><b>Not sure which plan is right for you?</b><p>Book a free placement call and we’ll guide you.</p><button onClick={()=>go('method')}>Book a Placement Call</button></aside></div></section>
<section id="faq" className="fl-wrap fl-section fl-faq"><div>{['How is my level determined?','What if I miss a live class?','Do you offer certificates?','Can I switch classes or schedules?','Is FluentPath 100% online?','What technology do I need?'].map((x,i)=><article key={x}><button onClick={()=>setFaq(faq===i?null:i)}>{x}<span>{faq===i?'−':'+'}</span></button>{faq===i&&<p>Our team makes it simple to find the right level and flexible path for you.</p>}</article>)}</div><aside><div className="fl-cta-placeholder">Live class<br/>placeholder</div><h2>Your next conversation<br/>starts here.</h2><p>Take the first step toward real progress.</p><button>Take the Placement Quiz</button><button className="ghost">Book a Placement Call</button></aside></section>
<footer className="fl-footer"><div className="fl-wrap"><div><a className="fl-logo" href="#top"><Globe2/><b>FluentPath</b><small>Languages</small></a><p>We help you speak with confidence.</p><span>f　◎　▶　in</span></div><Footer title="Programs" items={['English','Spanish','French','Arabic','German','IELTS & Business English']}/><Footer title="Quick Links" items={['About Us','Our Method','Instructors','Schedule','Outcomes','Pricing']}/><Footer title="Resources" items={['Blog','Learning Tips','Free Resources','Events','Career Opportunities']}/><Footer title="Contact" items={['hello@fluentpath.com','+1 (415) 555-0188','Mon – Fri, 9AM – 6PM','New York, USA']}/><div><h3>Stay Updated</h3><p>Join our newsletter for tips, events, and course updates.</p><input placeholder="Enter your email"/><button>Subscribe</button></div></div></footer>
</main>}
function Footer({title,items}:{title:string;items:string[]}){return <div><h3>{title}</h3>{items.map(x=><a href="#top" key={x}>{x}</a>)}</div>}
function FileIcon(){return <span>▧</span>}
function HeroCards(){return <div className="fl-hero-cards"><article><small>Your Progress</small><b>81%</b><strong>68%</strong><p>Overall Progress</p></article><article className="fl-convo"><small>Upcoming Conversation</small><b>Spanish Conversation Club</b><p>Wed, May 22 · 7:00 PM (EST)</p><button>Join Session</button></article><article><small>Vocabulary Streak　🔥</small><b>12 <em>days</em></b><p>Keep it going!</p><div className="fl-streak">▮ ▮ ▮ ▮ ▮ ▮ ▮</div></article><div className="fl-video">Live conversation<br/>placeholder</div><article><small>This Week</small><p>Mon　7:00 PM　Grammar & Usage</p><p>Wed　7:00 PM　Conversation Club</p><p>Fri　7:00 PM　Listening Lab</p></article></div>}
function Schedule(){return <div className="fl-schedule"><div>{['Time / Day','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map(x=><b key={x}>{x}</b>)}</div>{[['6:00 PM – 7:00 PM','Grammar & Usage','Listening Lab','Conversation Club','Grammar & Usage','Listening Lab','Weekend Intensive','Conversation Club'],['7:00 PM – 8:30 PM','Core Skills','Speaking Practice','Core Skills','Speaking Practice','Real-Life Scenarios','Weekend Intensive','—'],['8:30 PM – 9:00 PM','Office Hours','Office Hours','Office Hours','Office Hours','Office Hours','Q&A + Coaching','—']].map((r,i)=><div key={i}>{r.map(x=><span key={x}>{x}<small>{x.includes('PM')?'':' (Online Live)'}</small></span>)}</div>)}</div>}
